build:
  image: latest
python:
  version: 3.8
  setup_py_install: true
  before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - "./miniconda.sh -b"
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda update --yes conda
  install:
    - requirements: docs/requirements-doc.txt
    - pip install .[test,docs]
    - conda install -c conda-forge cython cyipopt pandas --yes
sphinx:
  configuration: docs/conf.py
