version: 2

build:
  image: latest
python:
 version: 3.7
 install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
          - docs
          - test
    - method: setuptools
      path: another/package
 system_packages: true
sphinx:
  configuration: docs/conf.py
