version: 2

build:
  image: latest
python:
 version: 3.7
 install:
    - requirements: docs/requirements-doc.txt
    - method: pip
      path: .
      extra_requirements:
          - docs
          - test
    - method: setuptools
      path: .
 system_packages: true
sphinx:
  configuration: docs/source/conf.py
