language: python
python:
- 3.7
before_install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b"
- export PATH=/home/travis/miniconda3/bin:$PATH
- conda update --yes conda
install:
- conda install -c conda-forge cyipopt --yes
- pip install .[test,docs]
script:
- make doctest -C docs/
- pytest
deploy:
  provider: pypi
  username: " __token__"
  password:
    secure: QrY0nkkXvnuXZSQRXjEY6Gdz79TKY5n0NljBA+AkOo0cUuCFHvieXdT4L/CTWMQyIaLzJfO7NjSfNjmCJDaXsYkfUALv7vixM6P83AqN7FZeTekbVcso2HvbefctoYc6pAm4VqkexgcXR4MV97X2hEKhPYPXhY3dY8F2VHaZW0MaA9Lqw4+JMTPORqVwqgH7vdoFs0c66RSq5MRRwTI00eO1/jLDU5/iHrYC+zmpxEBnw6+qQE9XpiAJ7hzx8Sqc05xr4P7nsu08MOYPXRSuhlLFg36cH7F1hCvXY9gINJ+tCW442x5aAwK7dx1+TKts4kcl/M3FiWSVVANC8rlmCwjgAALXQFbhEOnVidb9Y1IeLMbC8vG2j4XT7n9TPxvy1oBlnvqpZ4ceVEyS3Z8FYxsor94IbmqHD2shmi2yajx0hBzX3luj6vrAySnrviQyJ/nJWi5PqchAcx+2i21IZmdDNHiXqzgcMAhq2XeZiAyOrr44YZm4R1EJwAnGCDiw+VEqb0qche+2T+EcWMXEh7PMfUmgka+uzBaOtdkSj+B0eSihc9EySh2g54bOX0u+zM6hs/5iDYI7tcCFLv/mEYmbHtNSACYSw9EmcZOnkT1FpB3QqM3V/jNRykPLliYsgHGcUmgFL5u8u8yNGaVkVDwtgQ0tm1pJMNdgdYu7sJw=
  on:
    distributions: sdist bdist_wheel
    repo: ihmeuw-msca/anml
    tags: true
