language: python
python:
  - 3.7
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
` - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
install:
  - pip install .[test,docs]
  - conda install -c conda-forge cyipopt
script:
  - make doctest -C docs/
  - pytest
